# Generated by Django 6.0.1 on 2026-03-03 08:00

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('joined_date', models.DateField(null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=36)),
                ('monthly_amount', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=15), blank=True, default=list)),
                ('index_monthly_amount', models.IntegerField(default=0)),
                ('total_amount_of_money_in_the_category', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('withdrawal_addition_to_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('current_cash_balance_of_the_category', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('creation_date_of_the_category', models.DateField(null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('date_now', models.DateTimeField(null=True)),
                ('How_many_months_have_passed_since_the_category_was_created', models.IntegerField(null=True)),
                ('number_of_changes_deposit_amount', models.IntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='members.member')),
            ],
        ),
    ]
