# Generated by Django 6.0.1 on 2026-03-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_memberattribute_monthly_amount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberattribute',
            name='false_var',
            field=models.BooleanField(default=True),
        ),
    ]
