# Generated by Django 6.0.1 on 2026-03-07 00:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_memberattribute_false_var'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberattribute',
            name='monthly_amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=15), blank=True, default=list)),
        ),
    ]
