# Generated by Django 6.0.1 on 2026-03-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_memberattribute_monthly_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberattribute',
            name='total_monthly_payments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
