# Generated by Django 6.0.1 on 2026-03-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberattribute_total_monthly_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberattribute',
            name='category_name_new',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='new_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
