# Generated by Django 6.0.1 on 2026-02-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memberattribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberattribute',
            old_name='value',
            new_name='category',
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='creation_date_of_the_category',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='current_cash_balance_of_the_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='monthly_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='total_amount_of_money_in_the_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberattribute',
            name='withdrawal_addition_to_cash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberattribute',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='memberattribute',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='members.member'),
        ),
    ]
