# Generated by Django 6.0.1 on 2026-02-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_memberattribute_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberattribute',
            name='creation_date_of_the_category',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
