# Generated by Django 6.0.1 on 2026-02-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_memberattribute_creation_date_of_the_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberattribute',
            name='creation_date_of_the_category',
            field=models.DateField(null=True),
        ),
    ]
