# Generated by Django 6.0.1 on 2026-02-28 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_memberattribute_creation_date_of_the_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberattribute',
            name='date_now',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
