# Generated by Django 6.0.1 on 2026-02-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_memberattribute_date_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberattribute',
            name='How_many_months_have_passed_since_the_category_was_created',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='memberattribute',
            name='date_now',
            field=models.DateTimeField(null=True),
        ),
    ]
