# Generated by Django 6.0.1 on 2026-03-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_memberattribute_how_many_months_have_passed_since_the_category_was_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberattribute',
            name='number_of_changes_deposit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
