# Generated by Django 6.0.1 on 2026-03-03 05:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_memberattribute_number_of_changes_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberattribute',
            name='index_monthly_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memberattribute',
            name='monthly_amount',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=15), blank=True, null=True),
        ),
    ]
