# Generated by Django 6.0.1 on 2026-03-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_memberattribute_index_monthly_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberattribute',
            name='monthly_amount',
            field=models.JSONField(blank=True, null=True, verbose_name=models.DecimalField(decimal_places=2, max_digits=15)),
        ),
    ]
